version: '3'

services:

  mariadb:

    image: library/mariadb:10.3.28-focal
    container_name: escaperoomgame-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=escaperoomdb
    volumes:
      - C:\Users\dkern\Softwareprojekte\Docker\db\escaperoomgame:/var/lib/mariadb
    ports:
      - 3306:3306